services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: worlds_app
    ports:
      - "5050:5000"
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:latest
    container_name: worlds_grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - app
      - postgres

  postgres:
    image: postgres:16
    container_name: worlds_postgres
    restart: always
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: worlds
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mongo-data:
  db_data: