apiVersion: 1
datasources:
  - name: Worlds API
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://app:5000
    isDefault: true

  - name: WorldsDB
    type: postgres
    access: proxy
    url: db:5432
    database: worlds
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      sslmode: disable